module Sidetree
  HASH_ALGORITHM = "SHA256"
  HASH_PROTOCOL = "Multihash"
  DATA_ENCODING_SCHEME = "Base64URL"
  JSON_CANONICALIZATION_SCHEME = "JCS"
  KEY_ALGORITHM = ""
  SIGNATURE_ALGORITHM = ""
  CAS_PROTOCOL = ""
  CAS_URI_ALGORITHM = ""
  COMPRESSION_ALGORITHM= ""
  REVEAL_VALUE = 0x12
  GENESIS_TIME = 630000
  MAX_CORE_INDEX_FILE_SIZE = 1000000
  MAX_PROVISIONAL_INDEX_FILE_SIZE = 1000000
  MAX_PROOF_FILE_SIZE = 2500000
  MAX_CHUNK_FILE_SIZE = 10000000
  MAX_MEMORY_DECOMPRESSION_FACTOR = ""
  MAX_CAS_URI_LENGTH = 100
  MAX_DELTA_SIZE = 1000
  MAX_OPERATION_COUNT = 10000
  MAX_OPERATION_HASH_LENGTH = 100
  NONCE_SIZE = 16
end